config = {
    "BOT_TOKEN": "AAAAAAAAAAAA",
    "BOT_MANAGER": 12345,
    "TRANSLATIONS": {
        "en": {
            "BOT_GREETING_GROUP": "Hi! Thanks for adding me to this group chat, to send anoymous messages simply send me some text in private and i will resend it here",
            "BOT_GREETING_USER": "Hi! Just send me some messages and i will resend (not forward) them in the group",
            "REPORT": "Report this message",
            "BAN": "Ban this user",
            "UNWARN_NO_REPLY": "Reply to a user and his warns will be cleaned",
            "UNWARN_OK": "Ok! This user's warns are now gone",
            "WARN_REPORTER": "Warn reporter",
            "WARN_AUTHOR": "Warn author",
            "USER_NOT_ADMIN": "Sorry, you must be an admin to perform this action",
            "EMPTY_MSG": "Message is empty",
            "MSG_SENT": "Done! Anonymous message sent",
            "CANT_SEND": "Sorry, there were some problems sending the message to this chat, forward the message you tried to send to the bot manager along with this message:\n$message",
            "USER_IS_BANNED": "Sorry, you're banned from using the bot",
            "UNBAN_NO_REPLY": "Reply to a message and the author will be removed from the banned users",
            "UNBAN_OK": "Ok, user unbanned and warns cleared",
            "USER_WARNED_FOR_MESSAGE": "The user has already been warned for this message",
            "WARN_WRITE_REASON": "Write me the reason of this warn. Remember that if you get another report and press the warn button, you will lose any progress you made on this report",
            "WARN_WARNED_ALREADY_1": "Sorry, someone warned the user while you were writing a reason for his warn",
            "WARN_WARNED_ALREADY_2": "The user has already been warned for this messages",
            "WARN_WARNED": "Done, the user got a warn. Warn count: $warns/$max",
            "WARN_BANNED": "Sorry, you got warned enough times to earn yourself a ban",
            "WARN_WARNED_USER": "You got warned for one of your messages, reason:\n$reason\nYou're at $warns warn(s) out of $max",

            "GROUP_MEMS_ONLY": "Sorry, this command is restricted to group members only",
            "REPORTED_ADMIN_MSG": "<b>$reporter reported this message by $username:</b>\n\n$message",
            "REPORTED_REPLY": "Message reported, thank you",
            "USER_ALREADY_BANNED": "This user has been already banned",
            "USER_IS_ADMIN": "Sorry, this user is one of the bot admins and can't be banned/warned",
            "USER_BANNED": "Ok, user banned",
            "MAKEADMIN_NO_REPLY": "Reply to a message and the author will become an admin",
            "ADMIN_GREETING": "Welcome $admin to the admin team! Remember to start a private chat with the bot, if you haven't, or you won't receive reports",
            "REMOVEADMIN_NO_REPLY": "Reply to a message and the author will be removed from the admin team",
            "REMOVEADMIN_IS_MANAGER": "Sorry, can't remove the bot manager from the admins",
            "REMOVEADMIN_SUCCESS": "This user is not an admin at the moment",
            "REMOVEADMIN_USER_NOT_ADMIN": "$username is not an admin at the moment",
            "REPLY_ID_SAME_AS_BOT": "The bot can't be an admin of himself",
            "LIST_ADMINS_STRING": "List of the current admins:\n\n$admins",
            "SET_GROUP_OK": "Done! This will be the group i'm going to send anonymous messages to",
            "LOCALE_NO_REPLY": "Write a language and i will use it for my messages",
            "LOCALE_NOT_PRESENT": "Sorry, that locale isn't in my configuration! Ask the admins to add it in my configuration file",
            "LOCALE_SET": "Language changed to english",
            "ONLY_TEXT": "Sorry, to avoid sending NSFW content only text is allowed",
        },
    }
}
